CREATE TABLE t25(
	id INT,
	`name` VARCHAR(32)
	)
SHOW INDEXES FROM t25;
CREATE UNIQUE INDEX id_index ON t25(id);
CREATE INDEX id_index ON t25(id);
ALTER tabel t25 ADD INDEX id_index(id);
CREATE TABLE t26(
	`name` VARCHAR(32)
	id INT
);
ALTER TABLE t26 ADD PRIMARY KEY(id);
SHOW INDEX FROM t26;
DROP INDEX id_index ON t25;
ALTER TABLE t26 DROP PRIMARY KEY;
SHOW INDEX FROM t25;
SHOW INDEXES FROM t25;
SHOW KEYS FROM t25;
DESC  t25;
