CREATE TABLE t24 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(32) NOT NULL DEFAULT '',
    `name` VARCHAR(32) NOT NULL DEFAULT ''
);
INSERT INTO t24 VALUES(NULL, 'tom@qq.com', 'tom');
INSERT INTO t24 (email, `name`) VALUES ('mdl@sohu.com', 'mdl');
SELECT * FROM t24;
ALTER TABLE t25 AUTO_INCREMENT = 100;
CREATE TABLE t25 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(32) NOT NULL DEFAULT '',
    `name` VARCHAR(32) NOT NULL DEFAULT ''
);
INSERT INTO t25 VALUES(NULL, 'tom@qq.com', 'tom');
SELECT * FROM t25;