CREATE TABLE t27
	(id INT;
	`name` VARCHAR(32));
START TRANSACTION
SAVEPOINT a
INSERT INTO t27 VALUES(100,'tom');
SELECT * FROM t27;
SAVEPOINT b
INSERT INTO t27 VALUES(200,'jack');
ROLLBACK TO b;
ROLLBACK TO a;
